### PR TITLE
Add support for Python 3.12, drop support for Python 3.8

### PR DESCRIPTION
**Pull request by wilfried-huss**
### Summary

Add support for Python 3.12.

Because of [dependency conflicts](https://github.com/qiskit-community/qiskit-aqt-provider/pull/79#issuecomment-1832792249), remove support for Python 3.8. This major version is not actively supported since May 2021 and security support will end in October 2024.

### Details and comments

- update workflows to use Python 3.11 for non version-critical tasks;
- update tooling to use Python 3.9 as target version. This triggers using standard containers as type annotations instead of dedicated imports from the `typing` module;
- upgrade all dependencies. Qiskit dependencies are constrained further, to ensure Python 3.12 support:
  - Qiksit >= 0.45.2
  - Qistkit-Aer >= 0.13.2.

### CODE REVIEW

**Comment by airwoodix** [comment]
`symengine` 0.11 was released, with Python 3.12 wheels.
We can continue on this patch as soon as qiskit/qiskit#11262 is released.

**Comment by airwoodix** [comment]
Python 3.8 cannot be supported at the same time as Python 3.12, because `numpy` dropped support for Pyhton 3.8 in 1.25.0. Numpy >=1.26.0 is required for Python 3.12 support.

`qiskit-aer` doesn't ship Python 3.12 wheels yet. Building on demand fails. This may be fixed by qiskit/qiskit-aer#1947.

**Comment by mtreinish** [comment]
Aer has support for Python 3.12 now with https://github.com/Qiskit/qiskit-aer/pull/2022 which was recently published in 0.13.2.

**Comment by airwoodix** [comment]
@mtreinish thanks for the hint and the work on Python 3.12 support for Qiskit-Aer! It's great to have Python 3.12 support for all the dependencies in this package now.

@wilfried-huss I think this PR is ready now. Since you're the original author, I can only ask you for a review like this :)

**Review by alfrisch — APPROVED** [review]

**Pull request merged**
